api: 
  url: https://eval.contrastsecurity.com/Contrast
  api_key: T2ah1hNlP0YH0Va5QpxA29EwBbT7r6O9
  service_key: VSEMVASQ5QKUGS76
  user_name: agent_f8e6c707-90bb-476d-ab7c-0a23c10bb762@MartinKochloeflSeWorkshop
agent: 
  service: 
    enable: true
    logger: 
      path: contrast_service.log
      level: ERROR
    host: 127.0.0.1
    port: 30555
